services:
  - type: web
    name: raga-rasa-backend
    env: python
    plan: free
    runtime: python-3.10.13
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: EMOTION_SERVICE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_NAME
        value: raga_rasa
      - key: USE_EXTERNAL_EMOTION_SERVICE
        value: "true"
      - key: EMOTION_SERVICE_ENDPOINT
        value: /detect
