// Mock data for sessions, moods, and ragas

export const SESSION_HISTORY = [
  {
    id: "session_1",
    date: "2024-04-01",
    emotion: "Happy",
    raga: "Bhairav",
    duration: "45 min",
    rating: 4.5,
    moodBefore: 6,
    moodAfter: 8,
  },
  {
    id: "session_2",
    date: "2024-04-02",
    emotion: "Calm",
    raga: "Yaman",
    duration: "60 min",
    rating: 5,
    moodBefore: 5,
    moodAfter: 8,
  },
  {
    id: "session_3",
    date: "2024-04-03",
    emotion: "Energetic",
    raga: "Jog",
    duration: "30 min",
    rating: 4,
    moodBefore: 4,
    moodAfter: 7,
  },
  {
    id: "session_4",
    date: "2024-04-04",
    emotion: "Melancholic",
    raga: "Kharaharapriya",
    duration: "50 min",
    rating: 4.5,
    moodBefore: 3,
    moodAfter: 6,
  },
  {
    id: "session_5",
    date: "2024-04-05",
    emotion: "Peaceful",
    raga: "Ahir Bhairav",
    duration: "55 min",
    rating: 5,
    moodBefore: 5,
    moodAfter: 9,
  },
  {
    id: "session_6",
    date: "2024-04-06",
    emotion: "Happy",
    raga: "Bihag",
    duration: "40 min",
    rating: 4,
    moodBefore: 6,
    moodAfter: 9,
  },
  {
    id: "session_7",
    date: "2024-04-07",
    emotion: "Calm",
    raga: "Malhar",
    duration: "65 min",
    rating: 5,
    moodBefore: 4,
    moodAfter: 8,
  },
];

export const MOOD_TREND_DATA = [
  { session: "Session 1", before: 6, after: 8 },
  { session: "Session 2", before: 5, after: 8 },
  { session: "Session 3", before: 4, after: 7 },
  { session: "Session 4", before: 3, after: 6 },
  { session: "Session 5", before: 5, after: 9 },
  { session: "Session 6", before: 6, after: 9 },
  { session: "Session 7", before: 4, after: 8 },
];

export const EMOTION_DISTRIBUTION = [
  { name: "Happy", value: 35, fill: "#FCD34D" },
  { name: "Calm", value: 30, fill: "#60A5FA" },
  { name: "Energetic", value: 20, fill: "#F87171" },
  { name: "Sad", value: 10, fill: "#A78BFA" },
  { name: "Angry", value: 5, fill: "#FB7185" },
];

export const TOP_RAGAS = [
  {
    id: "1",
    name: "Bhairav",
    emotion: "Devotional",
    count: 45,
    favorite: true,
  },
  { id: "2", name: "Yaman", emotion: "Serene", count: 38, favorite: true },
  { id: "3", name: "Kharaharapriya", emotion: "Melancholic", count: 32, favorite: false },
  { id: "4", name: "Ahir Bhairav", emotion: "Peaceful", count: 28, favorite: true },
  { id: "5", name: "Jog", emotion: "Energetic", count: 25, favorite: false },
];

export const RAGAS = [
  {
    id: "1",
    name: "Bhairav",
    category: "Morning Ragas",
    emotion: "Devotional",
    arousal: "High",
    description: "A morning raga that inspires devotion and spiritual awakening",
  },
  {
    id: "2",
    name: "Yaman",
    category: "Evening Ragas",
    emotion: "Serene",
    arousal: "Low",
    description: "An evening raga that brings peace and tranquility",
  },
  {
    id: "3",
    name: "Kharaharapriya",
    category: "Night Ragas",
    emotion: "Melancholic",
    arousal: "Medium",
    description: "A night raga with a melancholic and introspective mood",
  },
  {
    id: "4",
    name: "Ahir Bhairav",
    category: "Night Ragas",
    emotion: "Peaceful",
    arousal: "Low",
    description: "A peaceful night raga for deep relaxation",
  },
  {
    id: "5",
    name: "Jog",
    category: "Evening Ragas",
    emotion: "Energetic",
    arousal: "High",
    description: "An energetic raga for uplifting the spirit",
  },
  {
    id: "6",
    name: "Malhar",
    category: "Monsoon Ragas",
    emotion: "Romantic",
    arousal: "Medium",
    description: "A romantic raga inspired by the monsoon season",
  },
  {
    id: "7",
    name: "Bihag",
    category: "Morning Ragas",
    emotion: "Joyful",
    arousal: "High",
    description: "A joyful morning raga that energizes the mind",
  },
  {
    id: "8",
    name: "Patdeep",
    category: "Night Ragas",
    emotion: "Calm",
    arousal: "Low",
    description: "A calm night raga for peaceful sleep",
  },
];
